
version: "3"

services:
  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    ports:
      - 80:80
    env_file:
      - db.env
    volumes:
      - nextcloud:/var/www/html

  mysql:
      platform: linux/x86_64
      image: mysql:8.0
      restart: unless-stopped
      env_file:
        - db.env
      volumes:
        - mysql:/var/lib/mysql

volumes:
  mysql:
  nextcloud: